name: Publish
on:
  release:
    types:
      - published
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore -p:Version=${{ github.event.release.tag_name }} -p:ContinuousIntegrationBuild=true
      - name: Test
        run: dotnet test -c Release --no-build
      - name: Publish ScoreHunter.PowerShell.csproj
        run: dotnet publish "src/ScoreHunter.PowerShell/ScoreHunter.PowerShell.csproj" -c Release --no-build -o "publish/ScoreHunter"
      - name: Create PowerShell module manifest
        shell: pwsh
        run: New-ModuleManifest -Path "publish/ScoreHunter/ScoreHunter.psd1" -RootModule "ScoreHunter.PowerShell.dll" -ModuleVersion "${{ github.event.release.tag_name }}" -Author "AnthoChamb" -Description "A score optimizer for GHTV's Score Chaser" -Copyright "Copyright (c) 2025 Anthony Chamberland" -ProjectUri "https://github.com/AnthoChamb/ScoreHunter" -LicenseUri "https://github.com/AnthoChamb/ScoreHunter/blob/main/LICENSE"
      - name: Publish PowerShell module
        shell: pwsh
        run: Publish-Module -Path "publish/ScoreHunter" -NuGetApiKey "${{ secrets.PSGALLERY_API_KEY }}"
